version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: globegenius123
      MONGO_INITDB_DATABASE: globegenius
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly no

  backend:
    build: ./backend
    depends_on:
      - mongodb
      - redis
    environment:
      - BREVO_API_KEY=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
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:globegenius123@mongodb:27017/globegenius?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-jwt-secret-key
      - GEMINI_API_KEY=AIzaSyDQZMYZJ2XRzZk9tHx_LcFvxkH-MgzQDqM
      - OPENAI_API_KEY=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
      - FLIGHTAPI_KEY=68931dee42373940c8aa9d9b
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend

  ml-service:
    build: ./ml-service
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service:/app

volumes:
  mongodb_data:
  redis_data: